# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74611faa8b64925f2b66f8148e6c913dc3c63ddb8255f2039df545d9db9184f81bfc7cf263f3917263cf03d87cf736653ff29cf9b33beebaffeb586947bc974c

test:
  secret_key_base: ea5cc32b1a83884f53a593c281e08cd22801cac75c0d968f8e32aae8e4e2188f2f17b39864ffbdc48f38a6582ce60bc8da712c930ef7c6ffb007956107e8155a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
